### PR TITLE
Fix license metadata in package.json

### PR DESCRIPTION
**Pull request by jayvdb**
See https://docs.npmjs.com/cli/v10/configuring-npm/package-json#license

### CODE REVIEW

**Comment by jayvdb** [comment]
ping @hejny

**Comment by jayvdb** [comment]
I've emailed Pavol about this and https://github.com/hejny/spacetrim/pull/10  in case he has missed the notification as I often do.

**Comment by hejny** [comment]
Thanks for the ping, merging and releasing new version with that change...

**Comment by hejny** [comment]
@jayvdb Thanks for the ping, merging and releasing new version with that change...

**Pull request merged**
