### PR TITLE
Add Edge path for linux

### PR DESCRIPTION
**Pull request by shirser121**

### CODE REVIEW

**Comment by shirser121** [comment]
@hejny what do you say?

**Comment by hejny** [comment]
Looks great 👍 thx

I will test it on Fedora+RHEL+Ubuntu and merge.

On which Linux distro(s) are you working?

**Comment by shirser121** [comment]
> Looks great 👍 thx
> 
> I will test it on Fedora+RHEL+Ubuntu and merge.
> 
> On which Linux distro(s) are you working?
> 
> ---
> 
> I even don't know that MS Edge is available on Linux 😃

I work on Ubuntu.
Just switch from locate-chrome to your package.

**Comment by hejny** [comment]
> > Looks great 👍 thx
> > 
> > I will test it on Fedora+RHEL+Ubuntu and merge.
> > 
> > On which Linux distro(s) are you working?
> > 
> > ---
> > 
> > I even don't know that MS Edge is available on Linux 😃
> 
> I work on Ubuntu.
> Just switch from locate-chrome to your package.


Working on misc distros.
Thanks for the contribution

**Pull request merged**
