### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
@hejny hi Pavol, could you take a look at this please.  I assume the CI failure is due to this PR coming from a fork.  Thank you!

**Comment by hejny** [comment]
Thanks for PRs, Where's exactly failing,what is the problematic dependency chain?

Your app
->
locate-app (2.4.43)
->
@promptbook/utils (0.70.0-1)
->
spacetrim (0.11.39)


---

If no, please write me, if yes, ill fix the problematic point + release new version of locate-app which doesn't use prerelease of Promptbook utils.

Tldr 

That's a misc utils and helpers for postprocessing and preprocessing text which goes in and put of llms and as it is both project I have created and there are functions usefull in locate app from theese utils. but we definitely don't need lastest versions of it because latest version is connected with LLAMA3 model which is totally irrelevant to locate-app

**Comment by jayvdb** [comment]
Hi one of the problems is the old userhome - it has been updated to fix the package.json license.  see https://github.com/shama/userhome/pull/3

**Comment by jayvdb** [comment]
The other one is we need the updated spacetrim , to include https://github.com/hejny/spacetrim/pull/10

**Comment by hejny** [comment]
@jayvdb Thanks for the contribution, I have just released [`locate-app` version `2.5.0`](https://www.npmjs.com/package/locate-app) which has fixed entire dependency chain:

- `@promptbook/utils` version `0.69.5`
- `type-fest` version `4.26.0`
- `userhome` version `1.0.1`
- `spacetrim` version `0.11.59`

**Pull request merged**
